In [50]:
import pandas as pd
import glob
from datetime import date

In [11]:
#pd.read_excel("Excel_files\Indeed_juniordata_2023-01-11.xlsx")

In [40]:
# getting xlsx files from the folder MyProject

#date="2023-01-
path = "Excel_files\Test"
#path="Excel_files\FILTERED_talent_juniordata_2023-01-05.xlsx"
filenames = glob.glob(path + "\*.xlsx")

# for file in filenames:
#     print(pd.read_excel(file))
df_list = (pd.read_excel(file) for file in filenames)

#pd.read_excel(path)

In [41]:
# Concatenate all DataFrames
df = pd.concat(df_list, ignore_index=True)
df

,job_title,company_name,company_location,job_desc,lan,link
0,Personal Trainer,Ultimate Performance,1016 Amsterdam Centrum\n+1 plaats,NaN,en,https://nl.indeed.com/pagead/clk?mo=r&ad=-6NYl...
1,(Junior) Procurement Specialist Rotterdam (m/w/d),Coolblue,Amsterdam\n+1 plaats,NaN,en,https://nl.indeed.com/pagead/clk?mo=r&ad=-6NYl...
2,"Regional Operations Manager, Uber Direct",Uber,Tijdelijk thuiswerken in 1097 Amsterdam,NaN,en,https://nl.indeed.com/pagead/clk?mo=r&ad=-6NYl...
3,(Junior) Category Manager Rotterdam (m/w/d),Coolblue,Amsterdam\n+1 plaats,NaN,en,https://nl.indeed.com/pagead/clk?mo=r&ad=-6NYl...
4,Junior Data Engineer,Independent Recruiters,Amsterdam\n+1 plaats,NaN,en,https://nl.indeed.com/pagead/clk?mo=r&ad=-6NYl...
...,...,...,...,...,...,...
236,Junior Sous ChefGeplaatst op: 02-01-2023,Ron Gastrobar Amsterdam,"Amsterdam, Noord-Holland",Wat voor jou!Bij Ron Gastrobar in Amsterdam zi...,nl,https://nl.talent.com/redirect?l=amsterdam&dat...
237,Junior Sous ChefGeplaatst op: 29-11-2022,Ron Gastrobar Oriental Downtown,"Amsterdam, Noord-Holland",Wat voor jou!Bij Ron Gastrobar in Amsterdam zi...,nl,https://nl.talent.com/redirect?l=amsterdam&dat...
238,Data Protection Officer,Exact,"Amsterdam, Noord-Holland",Senior Professional Job Delft Corporate Functi...,en,https://nl.talent.com/redirect?l=amsterdam&dat...
239,BI (business intelligence) / data specialist,ARQ Nationaal Psychotrauma Centrum,"Diemen, Noord-Holland",Wat ga je doen?Als BI (business intelligence)....,nl,https://nl.talent.com/redirect?l=amsterdam&dat...
240,Junior Compensations & Benefits Specialist,HMSHost,"Schiphol, Noord-Holland",Wat ga je doen als Junior Compensation & Benef...,nl,https://nl.talent.com/redirect?l=amsterdam&dat...

In [46]:
##FILTER/CLEAN THE DATA
## delete duplicates
filtered_df=df.drop_duplicates(subset=['job_title','company_name'])

In [48]:
#exclude ads not in english

filtered_df=df[df['lan']=='en']

In [49]:
filtered_df

,job_title,company_name,company_location,job_desc,lan,link
0,Personal Trainer,Ultimate Performance,1016 Amsterdam Centrum\n+1 plaats,NaN,en,https://nl.indeed.com/pagead/clk?mo=r&ad=-6NYl...
1,(Junior) Procurement Specialist Rotterdam (m/w/d),Coolblue,Amsterdam\n+1 plaats,NaN,en,https://nl.indeed.com/pagead/clk?mo=r&ad=-6NYl...
2,"Regional Operations Manager, Uber Direct",Uber,Tijdelijk thuiswerken in 1097 Amsterdam,NaN,en,https://nl.indeed.com/pagead/clk?mo=r&ad=-6NYl...
3,(Junior) Category Manager Rotterdam (m/w/d),Coolblue,Amsterdam\n+1 plaats,NaN,en,https://nl.indeed.com/pagead/clk?mo=r&ad=-6NYl...
4,Junior Data Engineer,Independent Recruiters,Amsterdam\n+1 plaats,NaN,en,https://nl.indeed.com/pagead/clk?mo=r&ad=-6NYl...
...,...,...,...,...,...,...
226,Data Analyst,Publitas,"Amsterdam, Noord-Holland",Do you know how to analyse and translate data ...,en,https://nl.talent.com/redirect?l=amsterdam&dat...
228,Mobilisation Project Manager - Data Centre Sol...,CBRE,"Amsterdam, Noord-Holland",Mobilisation Project Manager. Data Centre Solu...,en,https://nl.talent.com/redirect?l=amsterdam&dat...
229,Lead Consultant-IT Automation and Data Quality...,ITL Netherlands,"Amsterdam, Noord-Holland",YAML for components like ETL. DB. File System ...,en,https://nl.talent.com/redirect?l=amsterdam&dat...
230,Consumer Data Analyst Amsterdam,Projob B.V.,"Amsterdam, Noord-Holland",This role might be for you. We are looking for...,en,https://nl.talent.com/redirect?l=amsterdam&dat...
238,Data Protection Officer,Exact,"Amsterdam, Noord-Holland",Senior Professional Job Delft Corporate Functi...,en,https://nl.talent.com/redirect?l=amsterdam&dat...

In [51]:
# EXPORT DATAFRAME TO EXCEL
date=date.today()
filename=f"Excel_files/FILTERED_ALL_ADS_{date}.xlsx"
filtered_df.to_excel(filename,index=False)